### ISSUE TITLE
How to use it in Xcode 11.1

### ISSUE THREAD

**Issue by ctellez69** [SwiftUIExtensions/Grid#26]
Hello everyone,
And sorry for the dumb question: How do I use this package in my app? I have Xcode 11.1 and opened the GridExamples/GridExamples.xcodeproj file. I get several errors and I cannot run any of the examples. Particularly, I want to check the iOS one. These are the errors:

Showing Recent Issues
No account for team "Z8L4G5WZR3". (Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.)

If I want to use this extension, how do I include it in my project? 
I know this is so silly, but I am working on my first projects with Swiftui and I don't have much experience with Github, so please be gentle... :)
Thanks in advance!

**Comment by ay42** [comment]
@ctellez69 thank you for pointing this out. I removed our team identifier from this repo (#27) and now it should work in a simulator without any extra settings. If you want to run it on an actual device select you development profile here (Team dropdown menu):
<img width="1093" alt="Screen Shot 2019-11-06 at 11 16 55 AM" src="https://user-images.githubusercontent.com/2933241/68330107-80389c00-0087-11ea-9e21-69c0e9b764dc.png">

**Comment by ay42** [comment]
@ctellez69 make sure to update Grid version to 0.6.4 and let me know how it goes.

**Comment by ctellez69** [comment]
Hi ay42,
Thanks for the kind response and support. I am getting the following error:
![Screen Shot 2019-11-06 at 3 18 50 PM](https://user-images.githubusercontent.com/433983/68334581-e97cd700-00a8-11ea-938e-0fd34f0ea97a.png)

**Comment by ay42** [comment]
@ctellez69 Looks like you need to add a Github account to Xcode > Preferences > Accounts > `+`

**Comment by ctellez69** [comment]
My account is there, along with my apple id:
![Screen Shot 2019-11-06 at 3 44 19 PM](https://user-images.githubusercontent.com/433983/68336508-8ee57a00-00ac-11ea-8a5a-79efbb780702.png)

**Comment by ay42** [comment]
@ctellez69 link in GridExamples SwiftPM settings is a ssh link. Select default `SSH Key` from the dropdown menu and this should fix it.

**Comment by ay42** [comment]
@ctellez69 alternatively, you can update that link to `https://github.com/SwiftUIExtensions/Grid.git` and it should work as well.

**Comment by ctellez69** [comment]
Thanks Ay42. I changed to ssh and created a key... but still the same results.
I do appreciate your time.

**Comment by ay42** [comment]
@ctellez69 np. Can you double check that your ssh key is added to GitHub?
<img width="999" alt="Screen Shot 2019-11-06 at 1 02 34 PM 1" src="https://user-images.githubusercontent.com/2933241/68337772-11af0a80-0096-11ea-8c96-e1b39d997747.png">

**Comment by ctellez69** [comment]
Hi ay,
Yes, GitHUB even sent me a confirmation:

The following SSH key was added to your account:
Uploaded by Xcode - 2019-11-06 20:57:18 +0000
[...a series of numbers...]

**Comment by ay42** [comment]
@ctellez69 I'm out of ideas here, honestly.
Maybe this can help
https://forums.swift.org/t/pulling-private-spm-repos-in-xcode/25180

**Comment by ay42** [comment]
@ctellez69 also, try this in latest Xcode 11.2

**Comment by ctellez69** [comment]
Thanks ay42. I suspect 2 things:
- I am a total dumb
- I dont have an Apple Developer account. My account is from Apple developer... but I never paid the developer fee.
Thanks for all your help. I will check the link, update Xcode, and figure out how to get $100 to pay for my dev acct.
Best
